@startuml
object "Usuario : Jose " AS Usuario{
+username: admin
+password: admin
+Rol: superadministrador
}

object "Red : PDI/PAS" AS Red{
+name: PDI/PAS
}

object "Router : WAN2" AS Router{
+marca: CISCO
+series: 881
+NumeroModelo: CSG-CK9
+NumeroPuertos: 5
+IP: 172.142.10.0
+MAC: 00:00:5e:00:53:af
+username: admin
+password: admin
}

object "NumeroReferencia : Movistar" AS NumeroReferencia{
+NumeroTelefono: 123-321-456
}

object "Firewall : Zywall" AS Firewall{
+Marca: Zyxel
+Series: X
+NumeroModelo: USG310
+SistemaOperativo: Andrid 10
}

object "Switch : CISCO" AS Switch{
+Name: sw-uno
+IP: 172.27.0.1
+MAC: 00:00:5e:00:53:af
+username: admin
+password: admin
+Modelo: SG220-26-K9
+Marca: CISCO
}

object "Vlan : PDI/PAS" AS Vlan{
+Name: VlanPDI/PASS
+IP: 172.27.20.1
+Gateway: 172.27.0.1
}

object "Sistema : Planta1" AS Sistema{
+Name: Sistema-PC
+Tipo: Hardware
}

object "Dispositivo : P1" AS Dispositivo{
+IP: 172.182.20.45
+MAC: 00:00:5e:00:53:af
+Tipo: Ordenador
}

Usuario -- Red

Red -- Firewall
Red -- Switch
Red -- Router

NumeroReferencia -r-|> Router

Switch -- Vlan

Vlan -- Sistema

Sistema -- Dispositivo
@enduml