@startuml proyecto
/' Diagrama de Clases -> Diagrama de Objetos -> Diagrama de estados '/

class Red 
class Sistema
class Hardware
class Usuario
class Aviso

Red  -l-> Sistema  : Posee >
Red --> Hardware : Obtiene >
Red --> Usuario : Tiene >
Red --> Aviso : Realiza >

Sistema --|> SistemaDeVigilacion
Sistema --|> SistemaDeAlarmas

Red -r-|> RedAlumnos
Red -u-|> RedProfesores

Hardware --|> Switch
Hardware --|> Router

Aviso --|> Gmail

Usuario --|> TecnicosInternos
Usuario --|> TecnicosExternos

@enduml